// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5Deq-nYAGRLebf_rjHmeI9gJGt88r5E8',
    appId: '1:715543398729:web:eaa3d65869d6c2b5da3298',
    messagingSenderId: '715543398729',
    projectId: 'contact-app-f36c6',
    authDomain: 'contact-app-f36c6.firebaseapp.com',
    storageBucket: 'contact-app-f36c6.firebasestorage.app',
    measurementId: 'G-543DBDK3YV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMapTA2mvH2h6_Mig4jfB7PCRruDOp79I',
    appId: '1:715543398729:android:b50d9fe06151fc35da3298',
    messagingSenderId: '715543398729',
    projectId: 'contact-app-f36c6',
    storageBucket: 'contact-app-f36c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD58aeqEz9WGtdcRzPDvVQekbjJb74Nlv4',
    appId: '1:715543398729:ios:55e009db3f0c70cbda3298',
    messagingSenderId: '715543398729',
    projectId: 'contact-app-f36c6',
    storageBucket: 'contact-app-f36c6.firebasestorage.app',
    iosBundleId: 'com.example.contactingApp',
  );
}
